from datetime import datetime
from typing import List, Optional
from beanie import Document, PydanticObjectId
from pydantic import Field

class StudyRoadmap(Document):
    user_id: PydanticObjectId
    target_role: str
    daily_available_hours: float
    skill_level: str  # "beginner", "intermediate", "advanced"
    deadline: Optional[datetime] = None
    topics_to_learn: List[str]
    
    # Store structures generated by Gemini (Markdown or JSON representations)
    daily_plan: str
    weekly_roadmap: str
    monthly_roadmap: str
    recommendations: List[str] = Field(default_factory=list)
    learning_priorities: List[str] = Field(default_factory=list)
    
    created_at: datetime = Field(default_factory=datetime.utcnow)

    class Settings:
        name = "study_roadmaps"
